services:
  # Base de datos PostgreSQL
  ordermaster-v1-pg-db:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    container_name: ordermaster-v1-pg-db-container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - ${DB_PGSQL_PORT_PUBLIC}:5434
    volumes:
      - ordermaster-v1-pg-data:/var/lib/postgresql/data
      #- ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ordermaster-v1-pg-network:
        ipv4_address: 170.21.0.241
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5 # NÃºmero de intentos antes de marcar como no saludable
      start_period: 30s #Espera inicial antes de comenzar a comprobar(Dar tiempo a PostgreSQL inicie)
  ordermaster-v1-pg-adminer-bd:
      image: adminer
      container_name: ordermaster-v1-pg-adminer-bd-container
      restart: unless-stopped
    #  restart: always
      ports:
        - 8081:8080
      depends_on:
        - ordermaster-v1-pg-db
      networks:
        ordermaster-v1-pg-network:
          ipv4_address: 170.21.0.243

  ordermaster-v1-pg-pgadmin4-db:
    container_name: ordermaster-v1-pgadmin4-container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "ordermasterV1@postgres.org"
      PGADMIN_DEFAULT_PASSWORD: "ordermasterV12026"
    ports:
      - 16543:80
    depends_on:
      - ordermaster-v1-pg-db
    networks:
      ordermaster-v1-pg-network:
        ipv4_address: 170.21.0.252
networks:
  ordermaster-v1-pg-network:
    driver: bridge
    #driver_opts:
    #    parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 170.21.0.0/24
volumes:
  ordermaster-v1-pg-data:
    name: ordermaster-v1-pg-data-local
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_DATA_DIR_BD}
      o: bind
